### ISSUE TITLE
Flagged as Trojan after compiling

### ISSUE THREAD

**Issue by decodering22** [MouseUnSnag/MouseUnSnag#24]
I'm not sure why this would be flagged as a Trojan but it is on carbon black which is what my corp uses. Ran it through virustotal.com And it's flagged as Trojan as well and a couple different scanners.

The original executable that's already compiled and released is perfectly fine. Does it have something to do with signing or lack thereof?

Any ideas?

**Comment by patricknelson** [comment]
Yeah, not sure why you're getting that. The latest release is here: 
https://github.com/MouseUnSnag/MouseUnSnag/releases/tag/V2.2

And the actual `.exe` is here: 
https://github.com/MouseUnSnag/MouseUnSnag/releases/download/V2.2/MouseUnSnag.exe

And if you plop that `.exe` URL into VirusTotal, this is what comes out:
https://www.virustotal.com/gui/url/6b5df0bc4a3c9f40680c2b5ae02c0301f3800498875b6ca32eaa3703404e4a58

Can you link to your VirusTotal result? Maybe the version you provided *did* have some kind of trojan in it, maybe (although not from the source here on Github, but possibly added later).

**Comment by patricknelson** [comment]
p.s. That said, I do know that some corps are pretty locked down (rightfully so) and this does hook into and manipulate mouse movement a bit. So, that could be considered suspicious maybe. Carbon Black (which my company also uses, I have Carbon Black Cloud installed right now) is unfortunately not listed on Virus Total and the Mouse Unsnag version I'm using right now is the same one I linked you to.

**Comment by decodering22** [comment]
Hi,

I'm not sure how the results are different, i literally downloaded the v2.2 executable, uploaded it and it shows trojan 

https://www.virustotal.com/gui/file/026eea82a460dbcf8e059abcf74737aac887de11a3b48f6d77d6e99a35040aa6

I see the difference is you are linking github but I actually downloaded the exe to my desktop and uploaded it that way. Try it my way and you will see what I see.

**Comment by decodering22** [comment]
confirmed, downloaded again on a clean VM, same result

https://www.virustotal.com/gui/file/026eea82a460dbcf8e059abcf74737aac887de11a3b48f6d77d6e99a35040aa6

**Comment by patricknelson** [comment]
That's weird that the same exact file (which has the same SHA 256 body hash as the URL version) on one report shows that it's clean (without downloading) vs. the downloaded and uploaded version showing a totally different result. I don't really use that site but I assume it's because they have different uses/functions. Odd (or at least unintuitive).

Anyway yeah that said, I just got the same result you did after reuploading it. Not sure what to tell you except that @GrantMoyer built this version last year, maybe he knows more. I don't work much in native code, I'm a web developer and I ended up being a contributor since I tinker _a little bit_ in C# (and happened to be very adamant about fixing the issue in Windows that this app fixes). So, I really hope it doesn't have a trojan. 

Also, FWIW, what's funny is now that I know is clean that I built and uploaded myself on this very computer a few years ago (at https://github.com/patricknelson/MouseUnSnag/releases) does get blocked by Carbon Black. 😅 I'm guessing these apps are using heuristics. It's a binary that hasn't been seen before, it hooks into the mouse, etc. 🤷‍♂️ All conjecture here.

**Comment by patricknelson** [comment]
@GrantMoyer any ideas? You might know more about this than I do.

**Comment by decodering22** [comment]
Thanks for confirming, yea I'm perplexed why it behaves this way too. Could it be lack of signature bc it makes no sense for this to be a Trojan after looking at the code.

**Comment by patricknelson** [comment]
Since I'm not well versed in this (and thankfully this is open source) and you _happen_ to have the ability, feel free to clone the code and compile it yourself. I'm fairly certain it's safe, which is why I'm not too concerned. I don't know what it'd take to get it removed from those databases.

p.s. After some thought (it's been a while), I don't know for sure, but there's a possibility that in the past year or two, I convinced my IT to allow this app. So, it may just be explicitly listed which might be why "it works on my machine" with Carbon Black.

**Comment by decodering22** [comment]
I have compiled it and it got flagged originally so I took the executable and same results. It makes no sense, I'm just curious what could be causing it to get flagged than anything really

**Comment by GrantMoyer** [comment]
Thanks for the report @decodering22. Unfortunately, I'm not sure why it's being flagged, although I'm certain it's a false positive. I am not the original author of the code in this repo, but at some point I've looked through it all, and there's nothing malicious. A supply chain attack on my compiler is also exceedingly unlikely, since I built the executable in question on Linux using my distribution's mono packages, which are cryptographically verified.

Like, @patricknelson says though, MouseUnSnag's main function (changing the position of the cursor) is something that malware often does, so that could be part of the reason. I'll see if I can report the false positives to the relevant anti-malware vendors.

**Comment by decodering22** [comment]
No worries, I know it's not malicious but trying to convince others in a corp when they are not technical will be a challenge. I didn't see anything I could strip that would make it better so I figured why not ask here

**Comment by GrantMoyer** [comment]
I've submitted false positive reports to the three vendors reporting malware on VirtusTotal: Fortinet, SecureAge, and MaxSecure. However, I'm unable to find *any* support contact for VMWare Carbon Black, since I don't have a subscription to VMWare's service. Carbon Black's knowledge base article [How to report Malware False Positives to VMware Carbon Black][1] describes how to report a false positive, but I'm unable to register an account to open a support ticket as described.

[1]: https://community.carbonblack.com/t5/Knowledge-Base/All-Products-How-to-report-Malware-False-Positives-to-VMware/ta-p/101821

**Comment by decodering22** [comment]
Appreciate it.

**Comment by mbomb007** [comment]
Just an update: the VirusTotal links from above no longer show any false positives. Could this be closed?

**Comment by patricknelson** [comment]
I'd be happy to close it for now, sure. Thanks for the reminder @mbomb007.
