### ISSUE TITLE
Cannot jump drag some windows between monitors

### ISSUE THREAD

**Issue by mrandreastoth** [MouseUnSnag/MouseUnSnag#33]
Edition: Windows 10 Enterprise
Version: 22H2
OS build: 19045.4780
Experience: Windows Feature Experience Pack 1000.19060.1000.0

I have three monitors in the following configuration...

![image](https://github.com/user-attachments/assets/2f47a138-745f-43f8-8323-b04b037a9fcd)

I have MouseUnSnag configured with UnStick and Jump.

I also run Actual Window Manager 8.15.1 and several of the utilities that come with PowerToys 0.82.0.

Issue: Jump feature does not work when some windows have the focus.

Steps to reproduce...

1) Display Task Manager, ensure it has the focus
2) Try to perform a mouse jump (this would mean trying to move directly between monitors 2 and 3 in my configuration displayed above)

Behaviour: Mouse won't jump between monitors until the focus is taken away from the offending window (in this case Task Manager). Clicking the desktop is a safe "window" to shift the focus to to ensure the mouse jump will work.

Expected behaviour: Mouse jump takes place.

**Comment by patricknelson** [comment]
Sounds like maybe the Task Manager is running with admin privileges, but Mouse Unsnag isn't. See if that's the reason. 

Have you been able to reproduce this with any other apps aside from Task Manager? e.g. maybe command prompt? Try running `cmd.exe` (normally, unprivileged), then see if you can reproduce the issue when launching it in elevated mode (with administrator privileges). If that's the case, then I assume it's a permissions related thing, since the mouse I suppose is controlling an app with elevated privileges, so since Mouse UnSnag isn't privileged, it cannot alter the mouse. 

I noticed similar issues with AltDrag (another app that hooks into the mouse).

**Comment by mrandreastoth** [comment]
> Have you been able to reproduce this with any other apps aside from Task Manager?

Definitely, and definitely with ones running in user-mode. I'll update this ticket with other software that does this when I come across them.

**Comment by mrandreastoth** [comment]
Hmm, I stand corrected, it seems it may be for software that is running as administrator!

**Comment by patricknelson** [comment]
Ok, that's good news. In that case it's not something that could be solved by the app per se. My suggestion for now is to just run it as an admin (if this is a common problem), otherwise maybe just ignore it since it's not a bug.

**Comment by patricknelson** [comment]
FYI @mrandreastoth this came up again, see discussion at #36.
