### ISSUE TITLE
Document "Rescale Pointer between Screens" functionality

### ISSUE THREAD

**Issue by patricknelson** [MouseUnSnag/MouseUnSnag#8]
If we keep this feature, we should document and explain what "Rescale pointer between screens" does and why it's useful in MouseUnSnag. I noticed this was added in https://github.com/MouseUnSnag/MouseUnSnag/commit/2698a93645de86d235ceabf61dabe94fa654f8d4 but I'm not certain exactly what it does, but it is currently present in the `master` codebase.

@dale-roberts or @GrantMoyer are either of you familiar with this? If so, please elaborate. If not, maybe we should consider removing it.

**Comment by dale-roberts** [comment]
I was not involved with adding that feature, but it looks like what it is doing is trying to put the cursor on the new screen at the same proportional vertical height as the old screen. For example: if the cursor is leaving one screen, and is, say, 20% up from the bottom, then it will try to make the cursor 20% up on the new screen that it jumped to, even if the two screens have different pixel resolution.

I don't have a strong feeling either way about this feature, and it may even be undesirable depending on the monitor geometries (you might *want* the cursor to come off the top of one monitor, and wind up on the bottom of an adjacent monitor). It looks like it was added as a test to tinker with, but was not fully fleshed out, and it does not seem to take into account various possible relative monitor scenarios.

**Comment by GrantMoyer** [comment]
I haven't looked at this closely, but I assumed this was to deal with monitors with different DPI scaling. I haven't noticed any problems with my monitors (which have different DPIs), but I can check more closely later..

**Comment by patricknelson** [comment]
Ok, thanks for the clarification. It sounds like a reasonable thing to have, particularly since there could be unusual monitor arrangements (e.g. horizontal adjacent to vertical) with differing resolutions at which point the mouse could be snagged where you'll need to relocate it to the adjacent monitor at the correct position (thus the need to rescale).

We'll just need help testing and then documenting that.

**Comment by patricknelson** [comment]
Targeting this for v2.2 since the next release based on `master` will include this feature, so it'll make sense to have the documentation ready by then.

**Comment by patricknelson** [comment]
I'll take a stab at reviewing and testing this to see if I can document it accurately. But, since it was invented by someone else, @CSchwang could you please chime in to explain the MouseUnsnag "Rescale Pointer between Screens" feature that you created so that we can document it properly? 

Thanks!

**Comment by GrantMoyer** [comment]
From reading _MouseUnSnag/Logic.cs_, it looks like the rescale option moves the cursor to the same relative position as a proportion of the screen's edge when moving from one screen to another. It only works when for vertical edges (i.e. moving horizontally between screens), and only if the monitors top edges align. I guess the intent was to make the cursor move smoothly between monitors if a high DPI monitor was arranged next to a low DPI monitor of the same physical dimensions. Also, probably due to an oversight, it only activates if unstick or jump is enabled, and even then, inconsistently. The diagram below describes the behavior:

![rescale](https://user-images.githubusercontent.com/6333127/163076101-db350a57-2d8a-46ff-a8d9-06f6da8517bf.png)

To me, the behavior seems pretty unintuitive, and I'd be fine just removing this feature until or unless someone explicitly request it.
